apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          # 强亲和 \
          # kubectl label no wsl-ubuntu20.04 disktype=ssd
          # kubectl label --overwrite no wsl-ubuntu20.04 disktype=ssd1
          # kubectl label no wsl-ubuntu20.04 disktype-
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: disktype
                    operator: In
                    values:
                      - ssd
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
